Do the first stage of the final project
BLADBORNE/java-explore-with-me pull request #1
Opened 2024-09-04 19:03 UTC by BLADBORNE

2024-09-05 15:33 UTC, andrew-larkin requested changes
Привет! Местами нужно поправить, структурно выполнено корректно.

2024-09-05 15:33 UTC, andrew-larkin commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/Main.java
> +public class Main {
StatsClient - это spring boot проект. в нем необходимо настроить restTemplate и вызовы методов addHit() и getStats()

2024-09-05 15:33 UTC, andrew-larkin commented on ewm-stats-service/stats-dto/src/main/java/ru/practicum/dto/ViewStatsDto.java
> +import lombok.Getter;
в этот модуль также нужно добавить класс EndpointHitDto

2024-09-05 15:33 UTC, andrew-larkin commented on ewm-stats-service/stats-service/src/main/java/ru/practicum/controller/StatsController.java
> +
здесь должен сохраняться EndpointHit

2024-09-05 15:33 UTC, andrew-larkin commented on ewm-stats-service/stats-service/src/main/java/ru/practicum/controller/StatsController.java
> +    public void createHit(@RequestBody Stats stats) {
ResponseEntity. в качестве параметра - EndpointHitDto

2024-09-05 15:33 UTC, andrew-larkin commented on ewm-stats-service/stats-service/src/main/java/ru/practicum/model/Stats.java
> +public class Stats {
EndpointHit

2024-09-05 15:33 UTC, andrew-larkin commented on ewm-stats-service/stats-service/src/main/resources/application.properties
> +#spring.config.activate.on-profile=ci,test
закомментиронные настройки удаляем

2024-09-21 22:12 UTC, TyutterinYakov reviewed
Добрый вечер! Отметил оставшиеся недочеты) Хорошего вечера! Если возникнут вопросы по ревью - пиши в пачку, буду рад помочь🌃

2024-09-21 22:12 UTC, TyutterinYakov commented on ewm-main-service-spec/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Хорошо было бы указать версию проекта
`<version>${project.version}</version>`
https://habr.com/ru/articles/344480/

2024-09-21 22:12 UTC, TyutterinYakov commented on ewm-stats-service/stats-client/pom.xml
> +            <version>3.3.3</version>
Указание версии у зависимостей `org.springframework.boot` не требуется, так как она берется от родительского проекта, чтобы обеспечить полную совместимость)

2024-09-21 22:12 UTC, TyutterinYakov commented on ewm-stats-service/stats-client/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Хорошо было бы указать версию проекта
`<version>${project.version}</version>`
https://habr.com/ru/articles/344480/

2024-09-21 22:12 UTC, TyutterinYakov commented on ewm-stats-service/stats-client/src/main/java/ru/practicum/client/StatsClient.java
> +public class StatsClient {
Отсутствует метод для обращения к методу получения статистики

2024-09-21 22:12 UTC, TyutterinYakov commented on ewm-stats-service/stats-dto/pom.xml
> +            <version>2.17.2</version>
Зависимости, для которых требуется указание версий следует располагать в блоке `<dependencyManagement>` в родительском POM, а в дочерних указывать их уже без ее указания

2024-09-21 22:12 UTC, TyutterinYakov commented on ewm-stats-service/stats-dto/pom.xml
> +            <version>1.18.32</version>
Зависимости, для которых требуется указание версий следует располагать в блоке `<dependencyManagement>` в родительском POM, а в дочерних указывать их уже без ее указания

2024-09-21 22:12 UTC, TyutterinYakov commented on ewm-stats-service/stats-service/pom.xml
> +            <version>3.3.3</version>
Также указание версии не требуется)

2024-09-21 22:12 UTC, TyutterinYakov commented on ewm-stats-service/stats-service/pom.xml
> +            <version>42.7.3</version>
Зависимости, для которых требуется указание версий следует располагать в блоке `<dependencyManagement>` в родительском POM, а в дочерних указывать их уже без ее указания

2024-09-21 22:12 UTC, TyutterinYakov commented on ewm-stats-service/stats-service/pom.xml
> +            <version>8.0.1.Final</version>
Лучше использовать зависимость `spring-boot-starter-validation`, в которую входит уже все необходимое)

2024-09-21 22:12 UTC, TyutterinYakov commented on ewm-stats-service/stats-service/pom.xml
> +            <version>1.6.0</version>
Зависимости, для которых требуется указание версий следует располагать в блоке `<dependencyManagement>` в родительском POM, а в дочерних указывать их уже без ее указания

2024-09-21 22:12 UTC, TyutterinYakov commented on ewm-stats-service/stats-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Хорошо было бы указать версию проекта
`<version>${project.version}</version>`
https://habr.com/ru/articles/344480/

2024-09-23 05:37 UTC, TyutterinYakov approved these changes
Добрый день! Поздравляю с успешной сдачей первой части дипломного проекта :) Продуктивной работы над основной! Прекрасного дня и отличного настроения!🌅🎇

2024-09-23 05:37 UTC, TyutterinYakov commented on ewm-stats-service/stats-service/src/main/java/ru/practicum/controller/StatsErrorHandler.java
> +public class StatsErrorHandler {
В класс следует добавить логирование) Для этого достаточно использовать аннотацию из lombok ->> `@Slf4j`. Далее в каждый наш хендлер следует добавить логирование сообщения об ошибке)
Также хорошо было бы передать в лог сообщение об ошибке, а можно и весь трейс, чтобы в случае ошибки было проще разобраться, что именно произошло)
Кстати, при логгировании более эффективно использовать не конкатенацию, а заполнитель - placeholder `{}`
Например:
`log.debug("Получен статус 404 Not found {}", ex.getMessage(), ex);`

2024-09-23 08:17 UTC, merged